### ISSUE TITLE
Support couchdb 2

### ISSUE THREAD

**Issue by jiunwu** [dokku/dokku-couchdb#20] opened 2016-11-11 11:23 UTC
https://blog.couchdb.org/2016/07/25/the-road-to-couchdb-2-0/
CouchDB 2.0 is released for a while, is there any plan to support it in dokku ?

**Comment by josegonzalez** [comment] 2017-03-19 23:59
Duplicate of #5. If someone wants to take the time to upgrade the plugin to use the official image, great!

**Closed by josegonzalez** 2017-03-19 23:59 UTC
